---
title: "Neutralization_assays"
author: "Kenneth Matreyek"
date: "8/13/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
library(tidyverse)
library(gridExtra)
#install.packages("xlsx", dependencies = TRUE)  
#install.packages("ggpubr", dependencies = TRUE)
#library(ggpubr) #error: there is no package called ‘openxlsx’
```

```{r Read in data}
d200813 <- read.csv(file = "data/200813_attune.csv", header = T, stringsAsFactors = F)
d200814 <- read.csv(file = "data/200814_attune.csv", header = T, stringsAsFactors = F)
d200817 <- read.csv(file = "data/200817_attune.csv", header = T, stringsAsFactors = F)
d200824 <- read.csv(file = "data/200824_lsr2.csv", header = T, stringsAsFactors = F)
d200828 <- read.csv(file = "data/200828_attune.csv", header = T, stringsAsFactors = F)
d200923 <- read.csv(file = "data/200923_attune.csv", header = T, stringsAsFactors = F) %>% mutate(date = "200923")
d200924 <- read.csv(file = "data/200924_attune.csv", header = T, stringsAsFactors = F) %>% mutate(date = "200924")
d200930 <- read.csv(file = "data/200930_attune.csv", header = T, stringsAsFactors = F) %>% mutate(date = "200930")
d201005 <- read.csv(file = "data/201005_attune.csv", header = T, stringsAsFactors = F) %>% mutate(date = "201005")
d201007 <- read.csv(file = "data/201007_attune.csv", header = T, stringsAsFactors = F) %>% mutate(date = "201007")
```

```{r Normalize the data}
d200813$norm_grn <- d200813$pct_grn / d200813[d200813$serum == "none","pct_grn"]
d200813$norm_red <- d200813$pct_red / d200813[d200813$serum == "none","pct_red"]

d200814$norm_grn <- d200814$pct_grn / d200814[d200814$serum == "none","pct_grn"]
d200814$norm_red <- d200814$pct_red / d200814[d200814$serum == "none","pct_red"]

d200817$norm_grn <- d200817$pct_grn / d200817[d200817$serum == "none","pct_grn"]
d200817$norm_red <- d200817$pct_red / d200817[d200817$serum == "none","pct_red"]

d200824$norm_bfp <- d200824$pct_bfp / d200824[d200824$serum == "none","pct_bfp"]
d200824$norm_grn <- d200824$pct_grn / d200824[d200824$serum == "none","pct_grn"]
d200824$norm_red <- d200824$pct_red / d200824[d200824$serum == "none","pct_red"]

d200828$norm_grn <- d200828$pct_grn / mean(d200828[d200828$serum == "none","pct_grn"])

d200923$norm_bfp <- d200923$pct_bfp / d200923[d200923$serum == "none","pct_bfp"]
d200923$norm_grn <- d200923$pct_grn / d200923[d200923$serum == "none","pct_grn"]
d200923$norm_red <- d200923$pct_red / d200923[d200923$serum == "none","pct_red"]

d200924$norm_bfp <- d200924$pct_bfp / d200924[d200924$serum == "none","pct_bfp"]
d200924$norm_grn <- d200924$pct_grn / d200924[d200924$serum == "none","pct_grn"]
d200924$norm_red <- d200924$pct_red / d200924[d200924$serum == "none","pct_red"]

d200930$norm_bfp <- d200930$pct_bfp / d200930[d200930$serum == "none","pct_bfp"]
d200930$norm_grn <- d200930$pct_grn / d200930[d200930$serum == "none","pct_grn"]
d200930$norm_red <- d200930$pct_red / d200930[d200930$serum == "none","pct_red"]

d201005$norm_bfp <- d201005$pct_bfp / d201005[d201005$serum == "none","pct_bfp"]
d201005$norm_grn <- d201005$pct_grn / d201005[d201005$serum == "none","pct_grn"]
d201005$norm_red <- d201005$pct_red / d201005[d201005$serum == "none","pct_red"]

d201007$norm_bfp <- d201007$pct_bfp / d201007[d201007$serum == "none","pct_bfp"]
d201007$norm_grn <- d201007$pct_grn / d201007[d201007$serum == "none","pct_grn"]
d201007$norm_red <- d201007$pct_red / d201007[d201007$serum == "none","pct_red"]
```

```{r expt6 First attempt with individual sera}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200923[d200923$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d200923 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200923 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))
SARS2_pseudovirus_plot

SARS1_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1e-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200923[d200923$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200923 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum)) +
  geom_point(data = d200923 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum))
SARS1_pseudovirus_plot

ZdM_pseudovirus_plot2 <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200923[d200923$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200923 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d200923 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))
ZdM_pseudovirus_plot2

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, Chimera_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, SARS1_pseudovirus_plot, ZdM_pseudovirus_plot2, ncol=3, nrow=1)
arranged_plot
ggsave(file = "Output/Plots/Neutralization_results_6.pdf", arranged_plot, height = 3, width = 8)
```

```{r expt7 First attempt with individual sera}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200924[d200924$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d200924 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200924 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))
SARS2_pseudovirus_plot

SARS1_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1e-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200924[d200924$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200924 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum)) +
  geom_point(data = d200924 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum))
SARS1_pseudovirus_plot

ZdM_pseudovirus_plot2 <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200924[d200924$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200924 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d200924 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))
ZdM_pseudovirus_plot2

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, Chimera_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, SARS1_pseudovirus_plot, ZdM_pseudovirus_plot2, ncol=3, nrow=1)
arranged_plot
ggsave(file = "Output/Plots/Neutralization_results_7.pdf", arranged_plot, height = 3, width = 8)
```


```{r expt8 First attempt with individual sera}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200930[d200930$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d200930 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200930 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))
SARS2_pseudovirus_plot

SARS1_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1e-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200930[d200930$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200930 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum)) +
  geom_point(data = d200930 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum))
SARS1_pseudovirus_plot

ZdM_pseudovirus_plot2 <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200930[d200930$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200930 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d200930 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))
ZdM_pseudovirus_plot2

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, Chimera_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, SARS1_pseudovirus_plot, ZdM_pseudovirus_plot2, ncol=3, nrow=1)
arranged_plot
ggsave(file = "Output/Plots/Neutralization_results_8.pdf", arranged_plot, height = 3, width = 8)
```

```{r expt9 First attempt with individual sera}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d201005[d201005$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d201005 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d201005 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))
SARS2_pseudovirus_plot

SARS1_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1e-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d201005[d201005$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d201005 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum)) +
  geom_point(data = d201005 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum))
SARS1_pseudovirus_plot

ZdM_pseudovirus_plot2 <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d201005[d201005$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d201005 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d201005 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))
ZdM_pseudovirus_plot2

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, Chimera_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, SARS1_pseudovirus_plot, ZdM_pseudovirus_plot2, ncol=3, nrow=1)
arranged_plot
ggsave(file = "Output/Plots/Neutralization_results_9.pdf", arranged_plot, height = 3, width = 8)
```

```{r exp10 First attempt with individual sera}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d201007[d201007$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d201007 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d201007 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))
SARS2_pseudovirus_plot

SARS1_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1e-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d201007[d201007$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d201007 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum)) +
  geom_point(data = d201007 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum))
SARS1_pseudovirus_plot

ZdM_pseudovirus_plot2 <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(1E-1,1.3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d201007[d201007$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d201007 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d201007 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))
ZdM_pseudovirus_plot2

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, Chimera_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, SARS1_pseudovirus_plot, ZdM_pseudovirus_plot2, ncol=3, nrow=1)
arranged_plot
ggsave(file = "Output/Plots/Neutralization_results_10.pdf", arranged_plot, height = 3, width = 8)
```


```{r Replicates}
combined_neut_replicates <- rbind(d200923, d200924, d200930, d201005, d201007)
highlighted_samples <- c("JF5_neg", "JF5_pos")

individual_sera_highlight <- combined_neut_replicates %>% filter(serum %in% highlighted_samples) %>% 
  mutate(log_norm_blu = log10(norm_bfp), log_norm_grn = log10(norm_grn), log_norm_red = log10(norm_red), count = 1)
individual_sera_other <- combined_neut_replicates %>% filter(!(serum %in% highlighted_samples)) %>% 
  mutate(log_norm_blu = log10(norm_bfp), log_norm_grn = log10(norm_grn), log_norm_red = log10(norm_red), count = 1)

## These are the samples I want to have colored and have legends for
individual_sera_highlight_summarized <- individual_sera_highlight %>% group_by(serum, dilution) %>% 
  summarize(grn_log_ave = mean(log_norm_grn), blu_log_ave = mean(log_norm_blu), red_log_ave = mean(log_norm_red),
            grn_log_sd = sd(log_norm_grn), blu_log_sd = sd(log_norm_blu), red_log_sd = sd(log_norm_red), count = sum(count))

individual_sera_highlight_summarized$grn_geomean <- 10^individual_sera_highlight_summarized$grn_log_ave
individual_sera_highlight_summarized$blu_geomean <- 10^individual_sera_highlight_summarized$blu_log_ave
individual_sera_highlight_summarized$red_geomean <- 10^individual_sera_highlight_summarized$red_log_ave
individual_sera_highlight_summarized$grn_upper_ci <- 10^(individual_sera_highlight_summarized$grn_log_ave + individual_sera_highlight_summarized$grn_log_sd/sqrt(individual_sera_highlight_summarized$count-1)*1.96)
individual_sera_highlight_summarized$grn_lower_ci <- 10^(individual_sera_highlight_summarized$grn_log_ave - individual_sera_highlight_summarized$grn_log_sd/sqrt(individual_sera_highlight_summarized$count-1)*1.96)
individual_sera_highlight_summarized$blu_upper_ci <- 10^(individual_sera_highlight_summarized$blu_log_ave + individual_sera_highlight_summarized$blu_log_sd/sqrt(individual_sera_highlight_summarized$count-1)*1.96)
individual_sera_highlight_summarized$blu_lower_ci <- 10^(individual_sera_highlight_summarized$blu_log_ave - individual_sera_highlight_summarized$blu_log_sd/sqrt(individual_sera_highlight_summarized$count-1)*1.96)
individual_sera_highlight_summarized$red_upper_ci <- 10^(individual_sera_highlight_summarized$red_log_ave + individual_sera_highlight_summarized$red_log_sd/sqrt(individual_sera_highlight_summarized$count-1)*1.96)
individual_sera_highlight_summarized$red_lower_ci <- 10^(individual_sera_highlight_summarized$red_log_ave - individual_sera_highlight_summarized$red_log_sd/sqrt(individual_sera_highlight_summarized$count-1)*1.96)

## Add upper and lower SE until I get the rest of my replicates
individual_sera_highlight_summarized$grn_upper_se <- 10^(individual_sera_highlight_summarized$grn_log_ave + individual_sera_highlight_summarized$grn_log_sd/sqrt(individual_sera_highlight_summarized$count-1))
individual_sera_highlight_summarized$grn_lower_se <- 10^(individual_sera_highlight_summarized$grn_log_ave - individual_sera_highlight_summarized$grn_log_sd/sqrt(individual_sera_highlight_summarized$count-1))
individual_sera_highlight_summarized$blu_upper_se <- 10^(individual_sera_highlight_summarized$blu_log_ave + individual_sera_highlight_summarized$blu_log_sd/sqrt(individual_sera_highlight_summarized$count-1))
individual_sera_highlight_summarized$blu_lower_se <- 10^(individual_sera_highlight_summarized$blu_log_ave - individual_sera_highlight_summarized$blu_log_sd/sqrt(individual_sera_highlight_summarized$count-1))


## Now also do this for the ones I don't want colored in b/c it makes the plot too crowded
individual_sera_other_summarized <- individual_sera_other %>% group_by(serum, dilution) %>% 
  summarize(grn_log_ave = mean(log_norm_grn), blu_log_ave = mean(log_norm_blu), red_log_ave = mean(log_norm_red),
            grn_log_sd = sd(log_norm_grn), blu_log_sd = sd(log_norm_blu), red_log_sd = sd(log_norm_red), count = sum(count))

individual_sera_other_summarized$grn_geomean <- 10^individual_sera_other_summarized$grn_log_ave
individual_sera_other_summarized$blu_geomean <- 10^individual_sera_other_summarized$blu_log_ave
individual_sera_other_summarized$red_geomean <- 10^individual_sera_other_summarized$red_log_ave
individual_sera_other_summarized$grn_upper_ci <- 10^(individual_sera_other_summarized$grn_log_ave + individual_sera_other_summarized$grn_log_sd/sqrt(individual_sera_other_summarized$count-1)*1.96)
individual_sera_other_summarized$grn_lower_ci <- 10^(individual_sera_other_summarized$grn_log_ave - individual_sera_other_summarized$grn_log_sd/sqrt(individual_sera_other_summarized$count-1)*1.96)
individual_sera_other_summarized$blu_upper_ci <- 10^(individual_sera_other_summarized$blu_log_ave + individual_sera_other_summarized$blu_log_sd/sqrt(individual_sera_other_summarized$count-1)*1.96)
individual_sera_other_summarized$blu_lower_ci <- 10^(individual_sera_other_summarized$blu_log_ave - individual_sera_other_summarized$blu_log_sd/sqrt(individual_sera_other_summarized$count-1)*1.96)
individual_sera_other_summarized$red_upper_ci <- 10^(individual_sera_other_summarized$red_log_ave + individual_sera_other_summarized$red_log_sd/sqrt(individual_sera_other_summarized$count-1)*1.96)
individual_sera_other_summarized$red_lower_ci <- 10^(individual_sera_other_summarized$red_log_ave - individual_sera_other_summarized$red_log_sd/sqrt(individual_sera_other_summarized$count-1)*1.96)

plot_upper_y_limit <- 1.3
plot_lower_y_limit <- 1e-2
```


```{r Replicate plot to send to David Canaday}
sars2_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  ggtitle("SARS2") +
  scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = grn_lower_se, ymax = grn_upper_se, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum))
sars2_combined_neut_plot

sars1_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  ggtitle("SARS1") +
  scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = blu_lower_se, ymax = blu_upper_se, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum))
sars1_combined_neut_plot

zdm_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  ggtitle("ZdM") +
  scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = red_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = red_geomean, color = serum)) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = red_geomean, color = serum))
zdm_combined_neut_plot

combined_arranged_plot <- grid.arrange(sars2_combined_neut_plot, sars1_combined_neut_plot, ncol=1, nrow=2)
combined_arranged_plot
ggsave(file = "Output/Plots/Neutralization_results_standard_error.pdf", combined_arranged_plot, height = 4, width = 3)
```

```{r Negative pool data only}
Neg2_only_plot <- ggplot() + theme_bw() + 
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS-CoV-2") +
  scale_x_log10(limits = c(7,2500)) +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum == "JF5_neg"), aes(x = dilution, y = grn_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized %>% filter(serum == "JF5_neg"), aes(x = dilution, ymin = grn_lower_ci, ymax = grn_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum == "JF5_neg"), aes(x = dilution, y = grn_geomean, color = serum))
Neg2_only_plot

Neg1_only_plot <- ggplot() + theme_bw() + 
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS-COV") +
  scale_x_log10(limits = c(7,2500)) +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum == "JF5_neg"), aes(x = dilution, y = blu_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized %>% filter(serum == "JF5_neg"), aes(x = dilution, ymin = blu_lower_ci, ymax = blu_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum == "JF5_neg"), aes(x = dilution, y = blu_geomean, color = serum))
Neg1_only_plot

Neg_only_plot <- grid.arrange(Neg2_only_plot, Neg1_only_plot, ncol=2, nrow=1)
ggsave(file = "Output/Plots/Neg_only_plot.pdf", Neg_only_plot, height = 3, width = 6)
```

```{r With positive pool data}
Neg_pos2_plot <- ggplot() + theme_bw() + 
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS-CoV-2") +
  scale_x_log10(limits = c(7,2500)) +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = grn_lower_ci, ymax = grn_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum))
Neg_pos2_plot

Neg_pos1_plot <- ggplot() + theme_bw() + 
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS-CoV") +
  scale_x_log10(limits = c(7,2500)) +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = blu_lower_ci, ymax = blu_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum))
Neg_pos1_plot

Neg_pos_plot <- grid.arrange(Neg_pos2_plot, Neg_pos1_plot, ncol=2, nrow=1)
ggsave(file = "Output/Plots/Neg_pos_plot.pdf", Neg_pos_plot, height = 3, width = 6)
```


```{r}
sars2_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS-CoV-2") +
  scale_x_log10(limits = c(7,2500)) +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = grn_lower_ci, ymax = grn_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum))
sars2_combined_neut_plot


sars1_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS-CoV") +
  scale_x_log10(limits = c(7,2500)) +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = blu_lower_ci, ymax = blu_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum))
sars1_combined_neut_plot

With_individuals_plot <- grid.arrange(sars2_combined_neut_plot, sars1_combined_neut_plot, ncol=2, nrow=1)
ggsave(file = "Output/Plots/With_individuals_plot.pdf", With_individuals_plot, height = 3, width = 6)
```



```{r}

sars2_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS2") +
  scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = grn_lower_ci, ymax = grn_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum))
sars2_combined_neut_plot

sars1_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("SARS1") +
  scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = blu_lower_ci, ymax = blu_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum))
sars1_combined_neut_plot

vsv_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
  ggtitle("VSV") +
  scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = individual_sera_other_summarized %>% filter(serum != "none"), aes(x = dilution, y = red_geomean, fill = serum), color = "grey50", alpha = 0.2) +
  geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = red_geomean, color = serum)) +
  geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = red_lower_ci, ymax = red_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
  geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = red_geomean, color = serum))
vsv_combined_neut_plot

combined_arranged_plot <- grid.arrange(sars2_combined_neut_plot, sars1_combined_neut_plot, ncol=2, nrow=1)
ggsave(file = "Output/Plots/Neutralization_results_conf_intervals.pdf", combined_arranged_plot, height = 3, width = 6)
```

```{r Import plot for each sample vs controls}
individual_sera_names <- individual_sera_other_summarized %>% distinct(serum) %>% filter(serum != "none")

for(x in 1:nrow(individual_sera_names)){
  sample <- individual_sera_names$serum[x]
  individual_sera_other_summarized2 <- individual_sera_other_summarized %>% filter(serum == sample)
  
  sars2_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
    ggtitle("SARS2") +
    scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
    labs(x = "Dilution of serum", y = "Fold infection of no-serum") + ggtitle(sample) +
    geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum)) +
    geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = grn_lower_ci, ymax = grn_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
    geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean, color = serum)) +
    geom_line(data = individual_sera_other_summarized2 %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean), color = "black", alpha = 1) +
    geom_errorbar(data = individual_sera_other_summarized2, aes(x = dilution, ymin = grn_lower_ci, ymax = grn_upper_ci), alpha = 0.4, width = 0.2) +
    geom_point(data = individual_sera_other_summarized2 %>% filter(serum != "none"), aes(x = dilution, y = grn_geomean))
  sars2_combined_neut_plot
  
  sars1_combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank(), legend.position = "none") +
    ggtitle("SARS1") +
    scale_x_log10() +  scale_y_log10(limits = c(plot_lower_y_limit,plot_upper_y_limit), expand = c(0,0)) + 
    labs(x = "Dilution of serum", y = "Fold infection of no-serum") + ggtitle(sample) +
    geom_line(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum)) +
    geom_errorbar(data = individual_sera_highlight_summarized, aes(x = dilution, ymin = blu_lower_ci, ymax = blu_upper_ci, color = serum), alpha = 0.4, width = 0.2) +
    geom_point(data = individual_sera_highlight_summarized %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean, color = serum)) +
    geom_line(data = individual_sera_other_summarized2 %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean), color = "black", alpha = 1) +
    geom_errorbar(data = individual_sera_other_summarized2, aes(x = dilution, ymin = blu_lower_ci, ymax = blu_upper_ci), alpha = 0.4, width = 0.2) +
    geom_point(data = individual_sera_other_summarized2 %>% filter(serum != "none"), aes(x = dilution, y = blu_geomean))
  sars1_combined_neut_plot
  
  combined_arranged_plot <- grid.arrange(sars2_combined_neut_plot, sars1_combined_neut_plot, ncol=2, nrow=1)
  ggsave(file = paste("Output/Plots/",sample,".pdf",sep=""), combined_arranged_plot, height = 3, width = 6)
}
```

```{r Export data for Chris King}
combined_summarized1 <- rbind(individual_sera_highlight_summarized, individual_sera_other_summarized)
combined_summarized2 <- combined_summarized[,c("serum", "dilution", "grn_geomean", "grn_upper_ci", "grn_lower_ci", "blu_geomean", "blu_upper_ci", "blu_lower_ci")]
colnames(combined_summarized2) <- c("serum","dilution","sars2_geomean","sars2_upper_ci","sars2_lower_ci","sars1_geomean","sars1_upper_ci","sars1_lower_c1")
write.csv(file = "Output/Data/Summarized_data.csv", combined_summarized2, row.names = F)

individual_sera <- rbind(individual_sera_highlight, individual_sera_other)
individual_sera2 <- individual_sera[,c("serum", "dilution", "date","pct_grn", "pct_bfp", "norm_grn", "norm_bfp")]
colnames(individual_sera2) <- c("serum", "dilution", "date","pct_sars2", "pct_sars1", "norm_sars2", "norm_sars1")
write.csv(file = "Output/Data/Raw_data.csv", individual_sera2, row.names = F)
```

```{r Comparing the G752A and G828A cells}
d201007b <- read.csv(file = "data/201007b_attune.csv", header = T, stringsAsFactors = F) %>% mutate(date = "201007")

d201007b$norm_bfp <- d201007b$pct_bfp / d201007b[d201007b$serum == "none","pct_bfp"]
d201007b$norm_grn <- d201007b$pct_grn / d201007b[d201007b$serum == "none","pct_grn"]

d201007_min <- d201007[,c("serum","dilution","norm_grn","pct_grn")]
d201007b_min <- d201007b[,c("serum","dilution","norm_grn","pct_grn")]

cell_comparison <- cbind(d201007_min, d201007b_min[,c("norm_grn","pct_grn")])

colnames(cell_comparison) <- c("serum","dilution","g752a_norm","g752a_pct","g828a_norm","g828a_pct")

ggplot() + theme_bw() +
  geom_point(data = cell_comparison, aes(x = g752a, y = g828a, color = serum)) +
  scale_x_log10(limits = c(0.01,1.4)) + scale_y_log10(limits = c(0.01,1.4))
```














```{r }
if (!require("openxlsx")) {
  install.packages("openxlsx", dependencies = TRUE)
  library(openxlsx)}

if (!require("drc")) {
  install.packages("drc", dependencies = TRUE)
  library(drc)}

combined_summarized <- rbind(individual_sera_highlight_summarized, individual_sera_other_summarized)
all_sample_names <- combined_summarized %>% distinct(serum) %>% filter(serum != "none")
ic_table <- data.frame("serum" = all_sample_names$serum,"sars2_ic90" = NA, "sars2_ic50" = NA,"sars1_ic90" = NA, "sars1_ic50" = NA)

for(x in 1:nrow(all_sample_names)){
  temporary_subset <- combined_summarized %>% filter(serum == all_sample_names$serum[x])
  mod2 <- drm(data = temporary_subset, formula = grn_geomean ~ dilution, fct=LL.5())
  ic_obj <- ED(object = mod2, respLev = c(10,50), interval = "delta")
  ic_df <- data.frame(ic_obj)
  ic_table[x,"sars2_ic90"] <- ic_df$Estimate[1]
  ic_table[x,"sars2_ic50"] <- ic_df$Estimate[2]
  
  temporary_subset <- combined_summarized %>% filter(serum == all_sample_names$serum[x])
  mod2 <- drm(data = temporary_subset, formula = blu_geomean ~ dilution, fct=LL.5())
  ic_obj <- ED(object = mod2, respLev = c(10,50), interval = "delta")
  ic_df <- data.frame(ic_obj)
  ic_table[x,"sars1_ic90"] <- ic_df$Estimate[1]
  ic_table[x,"sars1_ic50"] <- ic_df$Estimate[2]
}

for(a in 1:nrow(ic_table)){
  for(b in 2:ncol(ic_table)){
    ic_table[a,b] <- round(as.numeric(ic_table[a,b]),2)
  }
}


```





```{r IC50 values for each infection }
if (!require("openxlsx")) {
  install.packages("openxlsx", dependencies = TRUE)
  library(openxlsx)}

if (!require("drc")) {
  install.packages("drc", dependencies = TRUE)
  library(drc)}

all_sample_names <- combined_neut_replicates %>% distinct(serum) %>% filter(serum != "none")
all_sample_dates <- combined_neut_replicates %>% distinct(date)

ic50_table <- data.frame(matrix(nrow = nrow(all_sample_names), ncol = nrow(all_sample_dates)))
rownames(ic50_table) <- all_sample_names$serum #; colnames(ic50_table) <- all_sample_dates$date

for(x in 1:nrow(all_sample_names)){
  for(y in 1:nrow(all_sample_dates)){
    temporary_subset <- combined_neut_replicates %>% filter(serum == all_sample_names$serum[x], date == all_sample_dates$date[y])
    mod2 <- drm(data = temporary_subset, formula = norm_grn ~ dilution, fct=LL.5())
    ic50 <- ED(object = mod2, respLev = c(10), interval = "delta")
    ic50_df <- data.frame(ic50)
    ic50_table[x,y] <- ic50_df$Estimate
  }
}

for(a in 1:nrow(ic50_table)){
  for(b in 1:ncol(ic50_table)){
    ic50_table[a,b] <- round(as.numeric(ic50_table[a,b]),2)
  }
}


```


```{r}




dose_calc <- d200923 %>% filter(serum == "JF5A_Pos")
dose_calc2 <- dose_calc[,c("dilution","norm_grn")]

#dose_calc_model <-drm(formula = dose_calc$norm_grn ~ dose_calc$dilution, fct = LL.4(names = c("Slope", "Lower Limit", "Upper Limit", "ED50")),upperl = c(Inf,0.001,100,Inf), lowerl = c(-Inf,0,99.999,-Inf))
#summary(dose_calc_model)

#https://stackoverflow.com/questions/27297241/effective-dose-ed-in-the-drc-package
ryegrass.m0 <- drm(rootl ~ conc, data = ryegrass, fct = LL.4(names=c("Slope","Lower Limit","Upper Limit","ED50")))
summary(ryegrass.m0)
plot(ryegrass.m0, broken=TRUE, xlab="Dose (mM)", ylab="Root length (cm)", lwd=2,  cex=1.2, cex.axis=1.2, ex.lab=1.2)


mod2 <- drm(data = dose_calc2, formula = norm_grn ~ dilution, fct=LL.5())
summary(mod2)
plot(mod2, broken=TRUE, xlab="Dilution", ylab="Norm SARS2 infection", lwd=2, cex=1.2, cex.axis=1.2, ex.lab=1.2)

ic_200824 <- ED(object = mod2, respLev = c(10,50,90), interval = "delta")


#mod1 <- drm(sars2_mean ~ dilution, data = dose_calc, type ="binomial", fct=LL.2())
#ED(mod1, c(10, 20, 50, 90, 99), interval = "delta", reference = "control")

ic_200824 <- ED(object = mod2, respLev = c(10,50,90), interval = "delta")
ic_200824_df <- data.frame(ic_200824)

#ic_200824_lower <- ED(mod1, c(10), interval = "delta")[3]
#ic_200824_upper <- ED(mod1, c(10), interval = "delta")[4]

SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_vline(xintercept = ic_200824_df[1,1], linetype = 2) + geom_vline(xintercept = ic_200824_df[2,1], linetype = 3)
SARS2_pseudovirus_plot
```











```{r Expt4 making IC50 curve for infections }
if (!require("openxlsx")) {
  install.packages("openxlsx", dependencies = TRUE)
  library(openxlsx)}

if (!require("drc")) {
  install.packages("drc", dependencies = TRUE)
  library(drc)}

dose_calc <- d200824 %>% filter(serum == "JF5A_Pos")
dose_calc2 <- dose_calc[,c("dilution","norm_grn")]

#dose_calc_model <-drm(formula = dose_calc$norm_grn ~ dose_calc$dilution, fct = LL.4(names = c("Slope", "Lower Limit", "Upper Limit", "ED50")),upperl = c(Inf,0.001,100,Inf), lowerl = c(-Inf,0,99.999,-Inf))
#summary(dose_calc_model)

#https://stackoverflow.com/questions/27297241/effective-dose-ed-in-the-drc-package
ryegrass.m0 <- drm(rootl ~ conc, data = ryegrass, fct = LL.4(names=c("Slope","Lower Limit","Upper Limit","ED50")))
summary(ryegrass.m0)
plot(ryegrass.m0, broken=TRUE, xlab="Dose (mM)", ylab="Root length (cm)", lwd=2,  cex=1.2, cex.axis=1.2, ex.lab=1.2)


mod2 <- drm(data = dose_calc2, formula = norm_grn ~ dilution, fct=LL.5())
summary(mod2)
plot(mod2, broken=TRUE, xlab="Dilution", ylab="Norm SARS2 infection", lwd=2, cex=1.2, cex.axis=1.2, ex.lab=1.2)

ic_200824 <- ED(object = mod2, respLev = c(10,50,90), interval = "delta")


#mod1 <- drm(sars2_mean ~ dilution, data = dose_calc, type ="binomial", fct=LL.2())
#ED(mod1, c(10, 20, 50, 90, 99), interval = "delta", reference = "control")

ic_200824 <- ED(object = mod2, respLev = c(50), interval = "delta")
ic_200824_df <- data.frame(ic_200824)

#ic_200824_lower <- ED(mod1, c(10), interval = "delta")[3]
#ic_200824_upper <- ED(mod1, c(10), interval = "delta")[4]

SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = 0.5) +
  geom_line(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_vline(xintercept = ic_200824_df[1,1], linetype = 2) + geom_vline(xintercept = ic_200824_df[2,1], linetype = 3)
SARS2_pseudovirus_plot
```

```{r Expt5 making IC50 curve for infections }
if (!require("drc")) {
  install.packages("drc", dependencies = TRUE)
  library(drc)}

dose_calc <- d200828 %>% filter(serum == "JF5A_Pos")
dose_calc2 <- dose_calc[,c("dilution","norm_grn")]

#dose_calc_model <-drm(formula = dose_calc$norm_grn ~ dose_calc$dilution, fct = LL.4(names = c("Slope", "Lower Limit", "Upper Limit", "ED50")),upperl = c(Inf,0.001,100,Inf), lowerl = c(-Inf,0,99.999,-Inf))
#summary(dose_calc_model)

#https://stackoverflow.com/questions/27297241/effective-dose-ed-in-the-drc-package
ryegrass.m0 <- drm(rootl ~ conc, data = ryegrass, fct = LL.4(names=c("Slope","Lower Limit","Upper Limit","ED50")))
summary(ryegrass.m0)
plot(ryegrass.m0, broken=TRUE, xlab="Dose (mM)", ylab="Root length (cm)", lwd=2,  cex=1.2, cex.axis=1.2, ex.lab=1.2)


mod2 <- drm(data = dose_calc2, formula = norm_grn ~ dilution, fct=LL.5())
summary(mod2)
plot(mod2, broken=TRUE, xlab="Dilution", ylab="Norm SARS2 infection", lwd=2, cex=1.2, cex.axis=1.2, ex.lab=1.2)

ic_200828 <- ED(object = mod2, respLev = c(10,50,90), interval = "delta")


#mod1 <- drm(norm_grn ~ dilution, data = dose_calc, type ="binomial", fct=LL.2())
#ED(mod1, c(10, 20, 50, 90, 99), interval = "delta", reference = "control")

ic_200828 <- ED(object = mod2, respLev = c(10,50,90), interval = "delta")
ic_200828_df <- data.frame(ic_200828)

#ic_200828_lower <- ED(mod1, c(10), interval = "delta")[3]
#ic_200828_upper <- ED(mod1, c(10), interval = "delta")[4]

SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_line(data = d200828 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200828 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_vline(xintercept = ic_200828_df[1,1], linetype = 2) + geom_vline(xintercept = ic_200828_df[2,1], linetype = 3)
SARS2_pseudovirus_plot
```

```{r}
ic50_ic90_summaries <- data.frame("expt" = c(200824,200828), "ic90" = c(ic_200824_df[1,1],ic_200828_df[1,1]), "ic50" = c(ic_200824_df[2,1],ic_200828_df[2,1]))



```





```{r IC50 curves for infections across multiple replicates}
d200813_model <- drm(data = d200813, formula = norm_grn ~ dilution, fct=LL.5())
```



## OLD AREA
```{r expt1}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10(limits = c(10,3e3)) +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200813[d200813$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d200813 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200813 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))

VSVG_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10(limits = c(10,3e3)) +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("VSV-G pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200813[d200813$serum == "none","norm_red"], linetype = 2) +
  geom_line(data = d200813 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d200813 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, VSVG_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, VSVG_pseudovirus_plot, ncol=2, nrow=1)

ggsave(file = "plots/Neutralization_results_1.pdf", arranged_plot, height = 3, width = 6)
```

```{r expt2}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10(limits = c(10,3e3)) +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200814[d200814$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d200814 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200814 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))

VSVG_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10(limits = c(10,3e3)) +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("VSV-G pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200814[d200814$serum == "none","norm_red"], linetype = 2) +
  geom_line(data = d200814 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d200814 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, VSVG_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, VSVG_pseudovirus_plot, ncol=2, nrow=1)

ggsave(file = "plots/Neutralization_results_2.pdf", arranged_plot, height = 3, width = 6)
```

```{r expt3}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10(limits = c(10,3e3)) +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200817[d200817$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d200817 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200817 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))

VSVG_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10(limits = c(10,3e3)) +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("VSV-G pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200817[d200817$serum == "none","norm_red"], linetype = 2) +
  geom_line(data = d200817 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d200817 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, VSVG_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, VSVG_pseudovirus_plot, ncol=2, nrow=1)

ggsave(file = "plots/Neutralization_results_3.pdf", arranged_plot, height = 3, width = 6)
```

```{r expt4}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200824[d200824$serum == "none","norm_grn"], linetype = 2) +
  geom_line(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))
SARS2_pseudovirus_plot

Chimera_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200824[d200824$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum)) +
  geom_point(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_bfp, color = serum))
Chimera_pseudovirus_plot

Chimera_pseudovirus_plot2 <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("Chimeric") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200824[d200824$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum)) +
  geom_point(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = norm_red, color = serum))
Chimera_pseudovirus_plot2

#arranged_plot <- ggarrange(SARS2_pseudovirus_plot, Chimera_pseudovirus_plot, ncol=2, nrow=1, common.legend = TRUE, legend="top")
arranged_plot <- grid.arrange(SARS2_pseudovirus_plot, Chimera_pseudovirus_plot, ncol=2, nrow=1)

arranged_plot

ggsave(file = "plots/Neutralization_results_4.pdf", arranged_plot, height = 3, width = 6)


d200824$sars2_mean <- rowMeans(d200824[,c("norm_grn", "norm_bfp")])

Combined_neut_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10() +  scale_y_log10(limits = c(8E-3,3)) + ggtitle("SARS2-RBDs") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = d200824[d200824$serum == "none","norm_blue"], linetype = 2) +
  geom_line(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = sars2_mean, color = serum)) +
  geom_point(data = d200824 %>% filter(serum != "none"), aes(x = dilution, y = sars2_mean, color = serum))
Combined_neut_plot
```

```{r expt5}
SARS2_pseudovirus_plot <- ggplot() + theme_bw() + theme(panel.grid.minor = element_blank()) +
  scale_x_log10(limits = c(10,1e5)) +  scale_y_log10(limits = c(8E-3,3)) + 
  ggtitle("SARS CoV-2 pseudovirus") +
  labs(x = "Dilution of serum", y = "Fold infection of no-serum") + 
  geom_hline(yintercept = mean(d200828[d200828$serum == "none","norm_grn"]), linetype = 2) +
  geom_line(data = d200828 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum)) +
  geom_point(data = d200828 %>% filter(serum != "none"), aes(x = dilution, y = norm_grn, color = serum))
SARS2_pseudovirus_plot

ggsave(file = "plots/Neutralization_results_5.pdf", SARS2_pseudovirus_plot, height = 3, width = 6)
```

